//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillingSymtemCSCV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmHistory
    {
        public int ID { get; set; }
        public int DrillId { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Tag { get; set; }
        public Nullable<decimal> TagValue { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> RecoveryTime { get; set; }
        public string AlarmLevel { get; set; }
        public Nullable<int> Dispose { get; set; }
        public string DisposeMan { get; set; }
        public Nullable<System.DateTime> DisposeTime { get; set; }
        public Nullable<System.DateTime> dataMakeTime { get; set; }
        public string dataMakeUser { get; set; }
        public string dataMakePGM { get; set; }
        public Nullable<System.DateTime> dataUpdTime { get; set; }
        public string dataUpdUser { get; set; }
        public string dataUpdPGM { get; set; }
        public Nullable<long> Count { get; set; }
    }
}
