//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillingSymtemCSCV2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrillOSEntities : DbContext
    {
        public DrillOSEntities()
            : base("name=DrillOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActivityStatus> ActivityStatus { get; set; }
        public DbSet<AlarmHistory> AlarmHistory { get; set; }
        public DbSet<AlarmHistoryTJ> AlarmHistoryTJ { get; set; }
        public DbSet<BushingSize> BushingSize { get; set; }
        public DbSet<BushingType> BushingType { get; set; }
        public DbSet<CurrentDrill> CurrentDrill { get; set; }
        public DbSet<Drill> Drill { get; set; }
        public DbSet<Driller> Driller { get; set; }
        public DbSet<DrillTag> DrillTag { get; set; }
        public DbSet<DrillTools> DrillTools { get; set; }
        public DbSet<Memo> Memo { get; set; }
        public DbSet<MemoContent> MemoContent { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<ReportData> ReportData { get; set; }
        public DbSet<Rota> Rota { get; set; }
        public DbSet<Table_BitRecord> Table_BitRecord { get; set; }
        public DbSet<Table_DrillingAssembly> Table_DrillingAssembly { get; set; }
        public DbSet<Table_MudChemicalsAdded> Table_MudChemicalsAdded { get; set; }
        public DbSet<Table_PumpNo> Table_PumpNo { get; set; }
        public DbSet<TagDictionary> TagDictionary { get; set; }
        public DbSet<UnitTransfer> UnitTransfer { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserTagRef> UserTagRef { get; set; }
        public DbSet<WebRecordTag> WebRecordTag { get; set; }
        public DbSet<WorkCode> WorkCode { get; set; }
        public DbSet<Worker> Worker { get; set; }
        public DbSet<WorkType> WorkType { get; set; }
    }
}
