//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillingSymtemCSCV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillTag
    {
        public int ID { get; set; }
        public int DrillId { get; set; }
        public string Tag { get; set; }
        public Nullable<decimal> DefaultFrom { get; set; }
        public Nullable<decimal> DefaultTo { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> HValue { get; set; }
        public Nullable<decimal> LValue { get; set; }
        public string Type { get; set; }
        public Nullable<int> AlarmFlag { get; set; }
        public Nullable<System.DateTime> dataMakeTime { get; set; }
        public string dataMakeUser { get; set; }
        public string dataMakePGM { get; set; }
        public Nullable<System.DateTime> dataUpdTime { get; set; }
        public string dataUpdUser { get; set; }
        public string dataUpdPGM { get; set; }
        public Nullable<bool> IsBool { get; set; }
        public Nullable<bool> HisActive { get; set; }
        public Nullable<bool> LisActive { get; set; }
    }
}
