//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillingSymtemCSCV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footage
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public float sum_footage { get; set; }
    }
}
