//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrillingSymtemCSCV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BitRecord
    {
        public int ID { get; set; }
        public string BitNo { get; set; }
        public string Size { get; set; }
        public string IADCCode { get; set; }
        public string SerialNO { get; set; }
        public string JETS { get; set; }
        public string TFA { get; set; }
        public string DepthOut { get; set; }
        public string DepthIn { get; set; }
        public string TotalDrilled { get; set; }
        public string TotalHours { get; set; }
        public Nullable<System.DateTime> dataMakeTime { get; set; }
        public string dataMakeUser { get; set; }
        public string dataMakePGM { get; set; }
        public Nullable<System.DateTime> dataUpdTime { get; set; }
        public string dataUpdUser { get; set; }
        public string dataUpdPGM { get; set; }
    }
}
